// lib/firebase_options.dart
//
// ╔══════════════════════════════════════════════════════════════════╗
// ║  UniTrack — Firebase Options                                     ║
// ║                                                                  ║
// ║  This file is normally AUTO-GENERATED by the FlutterFire CLI.   ║
// ║  The values below are PLACEHOLDER templates.                     ║
// ║                                                                  ║
// ║  ── How to generate your REAL file ──────────────────────────── ║
// ║                                                                  ║
// ║  Step 1: Install FlutterFire CLI (run once globally)            ║
// ║    dart pub global activate flutterfire_cli                      ║
// ║                                                                  ║
// ║  Step 2: Log in to Firebase                                      ║
// ║    firebase login                                                ║
// ║                                                                  ║
// ║  Step 3: Run FlutterFire configure in your project root          ║
// ║    flutterfire configure                                         ║
// ║    → Select your Firebase project                                ║
// ║    → Select platforms: Android ✓  iOS ✓  (Web optional)         ║
// ║    → This OVERWRITES this file with real values                  ║
// ║                                                                  ║
// ║  Alternatively: manually paste values from                       ║
// ║    Firebase Console → Project Settings → Your Apps               ║
// ║                                                                  ║
// ║  !! NEVER commit real API keys to a public repository !!         ║
// ║  Add firebase_options.dart to .gitignore if open-source.         ║
// ╚══════════════════════════════════════════════════════════════════╝

// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'UniTrack does not support macOS. '
          'Configure a macOS app in Firebase Console if needed.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'UniTrack does not support Windows. '
          'Configure a Windows app in Firebase Console if needed.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'UniTrack does not support Linux. '
          'Configure a Linux app in Firebase Console if needed.',
        );
      default:
        throw UnsupportedError('Unknown platform: $defaultTargetPlatform');
    }
  }

  // ─────────────────────────────────────────────────────────────────
  // ANDROID
  // Source: Firebase Console → Project Settings → Android App
  // File:   android/app/google-services.json  (also required!)
  // ─────────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    // Your Firebase project's API key for Android
    // Found in: google-services.json → client[0].api_key[0].current_key
    apiKey: 'AIzaSyCtDNiwriQ1GF2fmri-dFJd4v8ekWR_OUQ',

    // Firebase project App ID for Android
    // Format: 1:PROJECT_NUMBER:android:HASH
    // Found in: google-services.json → client[0].client_info.mobilesdk_app_id
    appId: '1:952469275946:android:6c730720b6d2d386db8a53',

    // Your Firebase project's sender ID (for FCM / notifications)
    // Found in: google-services.json → project_info.project_number
    messagingSenderId: '952469275946',

    // Your Firebase project ID
    // Format: your-project-id (no spaces, lowercase)
    // Found in: google-services.json → project_info.project_id
    projectId: 'uni-bus-locate',

    // Firebase Realtime Database URL
    // Format: https://your-project-id-default-rtdb.REGION.firebasedatabase.app
    // Found in: Firebase Console → Realtime Database → Data tab → URL at top
    // IMPORTANT for UniTrack: this is required for live bus tracking!
    databaseURL:
        'https://uni-bus-locate-default-rtdb.asia-southeast1.firebasedatabase.app',

    // Firebase Storage bucket (optional — UniTrack doesn't use Storage by default)
    // Format: your-project-id.appspot.com
    storageBucket: 'uni-bus-locate.firebasestorage.app',
  );

  // ─────────────────────────────────────────────────────────────────
  // iOS
  // Source: Firebase Console → Project Settings → iOS App
  // File:   ios/Runner/GoogleService-Info.plist  (also required!)
  // ─────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    // Your Firebase project's API key for iOS
    // Found in: GoogleService-Info.plist → API_KEY
    apiKey: 'YOUR_IOS_API_KEY',

    // Firebase project App ID for iOS
    // Format: 1:PROJECT_NUMBER:ios:HASH
    // Found in: GoogleService-Info.plist → GOOGLE_APP_ID
    appId: '1:000000000000:ios:0000000000000000',

    // Your Firebase project's sender ID
    // Found in: GoogleService-Info.plist → GCM_SENDER_ID
    messagingSenderId: '000000000000',

    // Your Firebase project ID
    // Found in: GoogleService-Info.plist → PROJECT_ID
    projectId: 'your-unitrack-project-id',

    // Firebase Realtime Database URL — same as Android
    databaseURL:
        'https://your-unitrack-project-id-default-rtdb.asia-southeast1.firebasedatabase.app',

    // Firebase Storage bucket
    storageBucket: 'your-unitrack-project-id.appspot.com',

    // iOS-specific: your app's reversed client ID
    // Found in: GoogleService-Info.plist → REVERSED_CLIENT_ID
    // Required for Google Sign-In on iOS (UniTrack uses custom auth but keep it)
    iosClientId: 'YOUR_IOS_CLIENT_ID',

    // iOS bundle ID registered in Firebase
    // Must match: Runner.xcodeproj → PRODUCT_BUNDLE_IDENTIFIER
    // Example:  com.yourcompany.unitrack
    iosBundleId: 'com.yourcompany.unitrack',
  );

  // ─────────────────────────────────────────────────────────────────
  // WEB (optional — UniTrack is mobile-first but included for
  // admin dashboards or future web support)
  // Source: Firebase Console → Project Settings → Web App
  // ─────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-unitrack-project-id',
    databaseURL:
        'https://your-unitrack-project-id-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'your-unitrack-project-id.appspot.com',
    // Web-only: your auth domain
    // Format: your-project-id.firebaseapp.com
    authDomain: 'your-unitrack-project-id.firebaseapp.com',
    // Web-only: measurement ID for Google Analytics (optional)
    // Format: G-XXXXXXXXXX
    measurementId: 'G-XXXXXXXXXX',
  );
}

// ═══════════════════════════════════════════════════════════════════
// FIREBASE REALTIME DATABASE RULES
// ═══════════════════════════════════════════════════════════════════
//
// Paste these rules into:
//   Firebase Console → Realtime Database → Rules tab
//
// ┌─────────────────────────────────────────────────────────────────┐
// │                                                                 │
// │  {                                                              │
// │    "rules": {                                                   │
// │      "users": {                                                 │
// │        "$uid": {                                                │
// │          ".read":  "$uid === auth.uid",                         │
// │          ".write": "$uid === auth.uid"                          │
// │        }                                                        │
// │      },                                                         │
// │      "buses": {                                                 │
// │        ".read": "auth !== null",                                │
// │        "$busId": {                                              │
// │          ".write": "auth !== null &&                            │
// │            root.child('users').child(auth.uid)                  │
// │              .child('role').val() === 'driver'"                 │
// │        }                                                        │
// │      },                                                         │
// │      "trips": {                                                 │
// │        ".read": "auth !== null",                                │
// │        ".write": "auth !== null"                                │
// │      }                                                          │
// │    }                                                            │
// │  }                                                              │
// │                                                                 │
// └─────────────────────────────────────────────────────────────────┘
//
// ── What these rules do ──────────────────────────────────────────
//
//  users/   → each user reads/writes only their own profile
//  buses/   → all authenticated users can READ live bus data
//             only drivers can WRITE (update lat/lng/speed)
//  trips/   → all authenticated users can read/write trip records
//
// ── Development shortcut (ONLY for local testing, NEVER in prod) ─
//
//  {
//    "rules": {
//      ".read":  true,
//      ".write": true
//    }
//  }
//
// ═══════════════════════════════════════════════════════════════════
// REQUIRED ANDROID FILES
// ═══════════════════════════════════════════════════════════════════
//
//  1. google-services.json
//     └── Place at: android/app/google-services.json
//     └── Download from: Firebase Console → Project Settings → Android
//
//  2. android/build.gradle  — add to dependencies{}:
//     classpath 'com.google.gms:google-services:4.4.0'
//
//  3. android/app/build.gradle  — add at the very bottom:
//     apply plugin: 'com.google.gms.google-services'
//
//  4. android/app/build.gradle  — ensure minSdkVersion >= 21:
//     minSdkVersion 21
//
// ═══════════════════════════════════════════════════════════════════
// REQUIRED iOS FILES
// ═══════════════════════════════════════════════════════════════════
//
//  1. GoogleService-Info.plist
//     └── Place at: ios/Runner/GoogleService-Info.plist
//     └── Download from: Firebase Console → Project Settings → iOS
//     └── Add to Xcode: Runner target → Copy Bundle Resources
//
//  2. ios/Podfile  — ensure platform is 12.0 or higher:
//     platform :ios, '12.0'
//
// ═══════════════════════════════════════════════════════════════════
// REQUIRED FIREBASE SERVICES TO ENABLE
// ═══════════════════════════════════════════════════════════════════
//
//  In Firebase Console, enable the following:
//
//  ✅ Authentication
//     → Sign-in method → Anonymous  (UniTrack uses ID-based auth)
//     → Or Email/Password if you prefer
//
//  ✅ Realtime Database
//     → Create database → Start in test mode (then apply rules above)
//     → Choose region closest to your university
//       (e.g. asia-southeast1 for Bangladesh/South Asia)
//
//  ✅ (Optional) Cloud Firestore — NOT needed for UniTrack
//     UniTrack uses Realtime Database for low-latency live GPS updates
//
// ═══════════════════════════════════════════════════════════════════
